Repository sofastack/sofa-ark, pull requests merged in 2018-08, with the labels that each got.

#87 upgrade version 0.4.1
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-samples/pom.xml
  sofa-ark-samples/sample-ark-plugin/README.md
  sofa-ark-samples/sample-ark-plugin/README_EN.md
  sofa-ark-samples/sample-ark-plugin/common/pom.xml
  sofa-ark-samples/sample-ark-plugin/plugin/pom.xml
  sofa-ark-samples/sample-ark-plugin/pom.xml
  sofa-ark-samples/sample-springboot-ark/README.md
  sofa-ark-samples/sample-springboot-ark/README_EN.md
  sofa-ark-samples/sample-springboot-ark/pom.xml
Labels: upgrade

#88 Fix a bug that package provided jar into the ark biz
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
Labels: bug

#98 Upgrade release
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-samples/pom.xml
  sofa-ark-samples/sample-ark-plugin/README.md
  sofa-ark-samples/sample-ark-plugin/README_EN.md
  sofa-ark-samples/sample-ark-plugin/common/pom.xml
  sofa-ark-samples/sample-ark-plugin/plugin/pom.xml
  sofa-ark-samples/sample-ark-plugin/pom.xml
  sofa-ark-samples/sample-springboot-ark/README.md
  sofa-ark-samples/sample-springboot-ark/README_EN.md
  sofa-ark-samples/sample-springboot-ark/pom.xml
Labels: upgrade

#102 Add telnet server switch to enable or disable.
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/session/StandardTelnetServerImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/ArkContainerTest.java
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/EnvironmentUtils.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
Labels: enhancement

#103 Fix fast exception, avoid to create lots of exceptions which would be swallowed.
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/ContainerClassLoader.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/UseFastConnectionExceptionsEnumeration.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassloader.java
Labels: bug

#105 Auto select port
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/session/StandardTelnetServerImpl.java
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/PortSelectUtils.java
  sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/PortSelectUtilsTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
Labels: enhancement

#106 Ygc optimize
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/Handler.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarFile.java
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/StringUtils.java
  sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/StringUtilsTest.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/JarWriter.java
Labels: enhancement

#112 fix classloader concurrency bug
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassloader.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/ClassloaderConcurrencyTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/testdata/classloader/ClassloaderTestClass.java
Labels: bug

#108 Fix shutdown npe
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
Labels: bug

#109 Compatible springboot2
  sofa-ark-parent/support/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java
Labels: enhancement

#115 Upgrade version to 0.5.0
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-samples/pom.xml
  sofa-ark-samples/sample-ark-plugin/README.md
  sofa-ark-samples/sample-ark-plugin/README_EN.md
  sofa-ark-samples/sample-ark-plugin/common/pom.xml
  sofa-ark-samples/sample-ark-plugin/plugin/pom.xml
  sofa-ark-samples/sample-ark-plugin/pom.xml
  sofa-ark-samples/sample-springboot-ark/README.md
  sofa-ark-samples/sample-springboot-ark/README_EN.md
  sofa-ark-samples/sample-springboot-ark/pom.xml
Labels: upgrade
