Repository sofastack/sofa-ark, pull requests merged in 2019-10, with the labels that each got.

#305 OnArkEnabled support PluginClassLoader
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/src/main/java/com/alipay/sofa/ark/springboot/condition/OnArkEnabled.java
Labels: First-time contributor, cla:yes, size/XS

#306 Handle ark classes when get class resource
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java
Labels: cla:yes, question, size/XS

#308 remove samples
  .travis.yml
  README.md
  sofa-ark-samples/README.md
  sofa-ark-samples/README_EN.md
  sofa-ark-samples/pom.xml
  sofa-ark-samples/sample-ark-plugin/README.md
  sofa-ark-samples/sample-ark-plugin/README_EN.md
  sofa-ark-samples/sample-ark-plugin/common/pom.xml
  sofa-ark-samples/sample-ark-plugin/common/src/main/java/com/alipay/sofa/ark/sample/SampleClassNotExported.java
  sofa-ark-samples/sample-ark-plugin/common/src/main/java/com/alipay/sofa/ark/sample/common/SampleClassExported.java
  sofa-ark-samples/sample-ark-plugin/common/src/main/resources/Sample_Resource_Exported
  sofa-ark-samples/sample-ark-plugin/common/src/main/resources/Sample_Resource_Not_Exported
  sofa-ark-samples/sample-ark-plugin/plugin/pom.xml
  sofa-ark-samples/sample-ark-plugin/plugin/src/main/java/com/alipay/sofa/ark/sample/activator/SamplePluginActivator.java
  sofa-ark-samples/sample-ark-plugin/plugin/src/main/java/com/alipay/sofa/ark/sample/facade/SamplePluginService.java
  sofa-ark-samples/sample-ark-plugin/plugin/src/main/java/com/alipay/sofa/ark/sample/impl/SamplePluginServiceImpl.java
  sofa-ark-samples/sample-ark-plugin/pom.xml
  sofa-ark-samples/sample-springboot-ark/README.md
  sofa-ark-samples/sample-springboot-ark/README_EN.md
  sofa-ark-samples/sample-springboot-ark/conf/ark/bootstrap.properties
  sofa-ark-samples/sample-springboot-ark/pom.xml
  sofa-ark-samples/sample-springboot-ark/src/main/java/com/alipay/sofa/ark/sample/facade/SampleService.java
  sofa-ark-samples/sample-springboot-ark/src/main/java/com/alipay/sofa/ark/sample/impl/SampleServiceImpl.java
  sofa-ark-samples/sample-springboot-ark/src/main/java/com/alipay/sofa/ark/sample/springbootdemo/SpringbootDemoApplication.java
  sofa-ark-samples/sample-springboot-ark/src/main/resources/META-INF/spring/service.xml
  sofa-ark-samples/sample-springboot-ark/src/main/resources/application.properties
  sofa-ark-samples/sample-springboot-ark/src/test/java/com/alipay/sofa/ark/sample/IntegrationTest.java
  sofa-ark-samples/sample-springboot-ark/src/test/java/com/alipay/sofa/ark/sample/JUnitTest.java
  sofa-ark-samples/sample-springboot-ark/src/test/java/com/alipay/sofa/ark/sample/TestNGTest.java
Labels: cla:yes, size/XXL

#313 Support telnet quit
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/session/NettyTelnetServer.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
Labels: size/XS

#316 fix issue 315
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
Labels: bug, cla:yes, size/XS

#319 update netty to 4.1.42.Fianl
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
Labels: cla:yes, size/XS

#320 Support biz extension
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/ExtensionLoaderStage.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoader.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/PluginClassLoader.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/extension/ExtensionLoaderServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/ClassLoaderHookTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/extension/ExtensionServiceTest.java
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/biz/BizFileGenerator.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/ArkServiceLoader.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/Extension.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/ExtensionLoaderService.java
Labels: cla:yes, size/L

#324 Fix testcase
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/test/TestClassLoader.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/BaseTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/ClassLoaderHookTest.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/listener/ArkTestNGAlterSuiteListener.java
Labels: bug, cla:yes, size/L

#323 Reasonable management of log-sofa-boot-starter
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
Labels: cla:yes, size/S
