Repository sofastack/sofa-ark, pull requests merged in 2020-12, with the labels that each got.

#431 Migrate CI provider from Travis CI to Github Actions.
  .github/workflows/build.yml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
Labels: cla:yes, size/S

#430 support extension excludes denpendencies from extra resources
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/ParseUtils.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/excludes.txt
Labels: cla:yes, size/L

#429 Support custom plugin extension
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/ExecutableArkBizJar.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/JarBizArchive.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/JarPluginArchive.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/PluginModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/plugin/PluginFactoryServiceImpl.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/archive/Archive.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/archive/PluginArchive.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/plugin/PluginFactoryService.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
Labels: cla:yes, size/L

#432 Fix typo
  README.md
Labels: First-time contributor, bug, cla:no, size/XS

#433 provide default value for avaliable
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
Labels: cla:yes, size/S

#435 prepare-release-1.1.6
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/api/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/M
