Repository sofastack/sofa-ark, pull requests merged in 2020-01, with the labels that each got.

#342 biz unregister improvement
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/event/EventAdminServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/BizCommandProviderTest.java
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
Labels: First-time contributor, cla:yes, size/S

#347 classloader registerAsParallelCapable
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AgentClassLoader.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoader.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/JDKDelegateClassLoader.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/PluginClassLoader.java
Labels: cla:yes, size/S

#348 support biz attributes
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
Labels: cla:yes, size/M
