Repository sofastack/sofa-ark, pull requests merged in 2022-09, with the labels that each got.

#563 reduce cache size
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/injection/InjectionServiceImpl.java
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/api/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoader.java
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/M

#559 sofa-ark-maven-plugin support build-info
  check_format.sh
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/git/GitInfo.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/git/JGitParser.java
  sofa-ark-parent/support/ark-tools/src/test/java/com/alipay/sofa/ark/tools/test/JGitParserTest.java
Labels: cla:yes, size/L

#567 fix artifact id parser
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/MavenUtilsTest.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
Labels: bug, cla:yes, size/L
