Repository sofastack/sofa-ark, pull requests merged in 2023-11, with the labels that each got.

#761 Lylingzhen add ut
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizManagerServiceImpl.java
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/ArtifactsLibrariesTest.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/MavenUtilsTest.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/dependency-tree-mock.txt
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkTomcatServletWebServerFactory.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkTomcatWebServer.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/springboot/web/ArkTomcatServletWebServerFactoryTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/springboot/web/ArkTomcatWebServerTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/springboot/BaseSpringApplication.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/resources/kill-tomcat.sh
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/LibraryCallback.java
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/XL

#765 format test action
  .github/workflows/linux_build.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/windows_build.yml
Labels: cla:yes, size/M

#768 add package steps
  conf/javax.json
  pom.xml
Labels: cla:yes, size/S

#749 add class info lookup command of telnet
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/retrieval/ClassInfoMethod.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/retrieval/ClassInfoVO.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/retrieval/InfoQueryCommandProvider.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/retrieval/ViewRender.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/retrieval/ClassInfoMethodTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/retrieval/InfoQueryCommandProviderTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/retrieval/ViewRenderTest.java
Labels: cla:yes, size/XL, First-time contributor

#771 add ut
  pom.xml
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/archive/ExplodedArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/archive/JarFileArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/resources/exploded-archive-test/META-INF/MANIFEST.MF
  sofa-ark-parent/core-impl/archive/src/test/resources/exploded-archive-test/example-jarinjarinjar.jar
  sofa-ark-parent/core-impl/archive/src/test/resources/exploded-archive-test/sample-biz.jar
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/JarWriter.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
  sofa-ark-parent/support/ark-tools/src/test/java/com/alipay/sofa/ark/tools/JarWriterTest.java
  sofa-ark-parent/support/ark-tools/src/test/java/com/alipay/sofa/ark/tools/LayoutsTest.java
  sofa-ark-parent/support/ark-tools/src/test/java/com/alipay/sofa/ark/tools/MainClassFinderTest.java
  sofa-ark-parent/support/ark-tools/src/test/java/com/alipay/sofa/ark/tools/RepackagerTest.java
  sofa-ark-parent/support/ark-tools/src/test/resources/conf/test-jar.jar
Labels: cla:yes, size/L

#773 fix packaging for both jdk 17 and jdk8
  pom.xml
Labels: bug, cla:yes, size/XS

#774 add release for jdk17 and jdk8
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: cla:yes, size/M

#775 update version
  pom.xml
Labels: cla:yes, size/XS

#776 update staging plugin version
  pom.xml
Labels: cla:yes, size/XS

#778 Add profiles
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  conf/javax.json
  pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
Labels: cla:yes, size/L

#777 fix release for jdk17
  .github/workflows/linux_unit_test.yml
  .github/workflows/snapshot.yml
  .github/workflows/windows_unit_test.yml
  conf/javax.json
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
Labels: bug, cla:yes, size/M

#782 remove jdk17
  .github/workflows/linux_unit_test.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .github/workflows/windows_unit_test.yml
  conf/javax.json
  pom.xml
Labels: cla:yes, size/L

#653 Ark2.0 support Netty plugin
  pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkReactiveAutoConfigure.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyReactiveWebServerFactory.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyWebServer.java
  sofa-ark-plugin/netty-ark-plugin/pom.xml
  sofa-ark-plugin/netty-ark-plugin/src/main/java/NettyPluginActivator.java
  sofa-ark-plugin/netty-ark-plugin/src/main/java/com/alipay/sofa/ark/netty/ArkNettyIdentification.java
  sofa-ark-plugin/netty-ark-plugin/src/main/java/com/alipay/sofa/ark/netty/EmbeddedServerServiceImpl.java
Labels: cla:yes, size/XL

#784 support spring cloud for base
  pom.xml
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/startup/EmbedSofaArkBootstrap.java
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/XS

#789 Suit 3.2.0
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/EmbedClassPathArchiveTest.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoader.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/JarLauncher.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoaderTest.java
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/L

#788 update guava or netty
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-plugin/config-ark-plugin/pom.xml
Labels: cla:yes, size/S

#798 Optimize to support spring webflux in ark
  .github/workflows/codecov.yml
  .github/workflows/linux_unit_test.yml
  .github/workflows/windows_unit_test.yml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkReactiveAutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkServletAutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkCompositeReactorHttpHandlerAdapter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyReactiveWebServerFactory.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyWebServer.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  sofa-ark-plugin/netty-ark-plugin/pom.xml
  sofa-ark-plugin/netty-ark-plugin/src/main/java/com/alipay/sofa/ark/NettyPluginActivator.java
Labels: cla:yes, size/L

#797 Add Code Scan Action
  .github/workflows/cloud_code_scan.yml
Labels: cla:yes, First-time contributor, size/S
