Repository sofastack/sofa-ark, pull requests merged in 2023-02, with the labels that each got.

#607 修复插件declared-libraries的解析赋值
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java
Labels: cla:yes, size/M, First-time contributor

#608 optimize jar artifact id parse
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/archive/JarFileArchive.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarFile.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/api/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/JarUtils.java
  sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/JarUtilsTest.java
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/XL

#609 update to 2.1.1
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/api/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/M
