Repository sofastack/sofa-ark, pull requests merged in 2023-10, with the labels that each got.

#599 Add security policy
  SECURITY.md
Labels: cla:yes, size/XS

#731 Load artifact id from pom.xml file
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
Labels: cla:yes, size/M, First-time contributor, 2.2.4

#644 Fix single host tomcat classloader exception
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/XS, wait for feedback

#693 Create inactive_issues_robot.yml
  .github/workflows/inactive_issues_robot.yml
Labels: cla:yes, size/M

#757 修复tomcat版本冲突
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/XS

#603 feat: support soft link java agent
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/ClassLoaderUtils.java
Labels: cla:yes, size/XS, First-time contributor

#744 support apollo config for issue #601
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-plugin/config-ark-plugin/DEMO_SHOW.md
  sofa-ark-plugin/config-ark-plugin/README.md
  sofa-ark-plugin/config-ark-plugin/images/err_page.png
  sofa-ark-plugin/config-ark-plugin/images/master_biz.png
  sofa-ark-plugin/config-ark-plugin/images/message_log.png
  sofa-ark-plugin/config-ark-plugin/images/ok_page.png
  sofa-ark-plugin/config-ark-plugin/img.png
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/ConfigBaseActivator.java
  sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/ConfigTypeEnum.java
  sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/LazyActivatorWrapper.java
  sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/apollo/ApolloConfigActivator.java
  sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/zk/ZookeeperConfigActivator.java
  sofa-ark-plugin/config-ark-plugin/src/test/java/com/alipay/sofa/ark/config/ApolloConfigActivatorTest.java
  sofa-ark-plugin/config-ark-plugin/src/test/java/com/alipay/sofa/ark/config/ConfigBaseActivatorTest.java
  sofa-ark-plugin/config-ark-plugin/src/test/java/com/alipay/sofa/ark/config/MockApolloConfig.java
Labels: cla:yes, size/XL, First-time contributor

#758 add test coverage for ark plugin
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/M
