Repository sofastack/sofa-ark, pull requests merged in 2023-01, with the labels that each got.

#595 optimize jar package
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/api/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/MavenUtils.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/MavenUtilsTest.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/ArtifactItem.java
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes

#598 fix artifactid match
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
Labels: bug, cla:yes, size/XS

#597 optimize static combine deploy
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/DeployBizStage.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/DefaultBizDeployer.java
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkConfigs.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/MavenUtils.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkDeployStaticBizListener.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/startup/EmbedSofaArkBootstrap.java
Labels: cla:yes, size/L

#604 change version to 2.1.0
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/api/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/M
