Repository sofastack/sofa-ark, pull requests merged in 2023-08, with the labels that each got.

#686 remove invalid package #685
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
Labels: cla:yes, size/XS, First-time contributor

#673 Dev remove tomcat dependency
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/XS

#692 feat: 使用revision实现Maven模块统一版本管理
  .gitignore
  change_version.sh
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/api/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/M

#694 modify ark version name
  .gitignore
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/assembly/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core-impl/pom.xml
  sofa-ark-parent/core/api/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/core/exception/pom.xml
  sofa-ark-parent/core/pom.xml
  sofa-ark-parent/core/spi/pom.xml
  sofa-ark-parent/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-common-springboot/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-parent/support/ark-tools/pom.xml
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/M

#677 fix_unit_test
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/ClassLoaderUtilTest.java
  sofa-ark-parent/core/spi/src/test/java/com/alipay/sofa/ark/spi/argument/LaunchCommandTest.java
Labels: bug, cla:yes, size/M

#664 com.alipay.sofa.ark.loader.jar.JarUtils.parseArtifactId add parser
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
  sofa-ark-parent/core-impl/archive/src/test/resources/example-jarinjarinjar.jar
Labels: cla:yes, size/M

#698 fix: 解决解析带有空格路径的Jar包时抛FileNotfoundException的问题
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
Labels: bug, cla:yes, size/S

#695 Support use biz classloader define app classloader class in org.springframework.cglib.core.ReflectUtils.defineClass
  pom.xml
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoader.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
Labels: cla:yes, First-time contributor, size/S

#707 Test base package goal
  pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/MavenUtils.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/PackageBaseFacadeMojo.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/ArtifactItem.java
Labels: size/XL, First-time contributor, cla:no

#705 The cglib proxy class cannot be delegate to the master
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/DelegateToMasterBizClassLoaderHook.java
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/DefaultClassLoaderHookTest.java
Labels: cla:yes, size/M

#709 change version to 2.2.2
  pom.xml
Labels: cla:yes, size/XS

#711 Test base package goal
  pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/PackageBaseFacadeMojo.java
Labels: First-time contributor, size/S, cla:no

#708 update arkclient (add pluginManagerService for arklet)
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/ArkServiceContainer.java
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
Labels: cla:yes, First-time contributor, size/S
