Repository sofastack/sofa-ark, pull requests merged in 2023-09, with the labels that each got.

#717 support disableGitInfo
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/git/JGitParser.java
Labels: cla:yes, size/S

#719 support to build biz with jdk17
  sofa-ark-bom/pom.xml
Labels: cla:yes, size/XS

#713 Test base package goal
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/PackageBaseFacadeMojo.java
Labels: size/M, First-time contributor, cla:no

#721 更简单的方式处理exclude和间接依赖
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/PackageBaseFacadeMojo.java
Labels: size/L, First-time contributor, cla:no

#722 fix path error
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/PackageBaseFacadeMojo.java
Labels: bug, First-time contributor, size/S, cla:no

#723 fix path error
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/PackageBaseFacadeMojo.java
Labels: bug, First-time contributor, size/S, cla:no

#725 change version to 2.2.3
  pom.xml
Labels: cla:yes, size/XS

#727 add release by github action workflow
  .github/workflows/release.yml
Labels: cla:yes, size/M

#733 support inner classes for jdk17
  sofa-ark-bom/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/MainClassFinder.java
Labels: cla:yes, size/XS

#735 wildcard match support both * and .*
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
Labels: cla:yes, size/M

#742 enable gpg to release in github action workflow
  pom.xml
Labels: cla:yes, size/XS
