Repository sofastack/sofa-ark, pull requests merged in 2024-07, with the labels that each got.

#948 Lipeng fix module slim read ark config
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/conf/ark/bootstrap.properties
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/conf/ark/bootstrap.yml
Labels: bug, cla:yes, size/S

#955 add biz state change msg
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizManagerServiceImpl.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
Labels: cla:yes, size/L

#959 fix set url when create biz
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
Labels: bug, question, cla:yes, size/S

#949 统一静态合并部署
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/EmbedClassPathArchiveTest.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/extension/ExtensionLoaderServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/ArkContainerTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/BaseTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/hook/TestAddBizToStaticDeployHook.java
  sofa-ark-parent/core-impl/container/src/test/resources/META-INF/services/sofa-ark/com.alipay.sofa.ark.spi.service.biz.AddBizToStaticDeployHook
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/biz/AddBizToStaticDeployHook.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/ArkServiceLoader.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/ExtensionLoaderService.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/AddBizInResourcesHook.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/MasterBizEnvironmentHolder.java
  sofa-ark-parent/support/ark-support-starter/src/main/resources/META-INF/services/sofa-ark/com.alipay.sofa.ark.spi.service.biz.AddBizToStaticDeployHook
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/AddBizInResourcesHookTest.java
  sofa-ark-parent/support/ark-support-starter/src/test/resources/SOFA-ARK/biz/biz1-bootstrap-0.0.1-SNAPSHOT-ark-biz.jar
Labels: cla:yes, size/XL

#960 修改资源静态合并部署的配置位置
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkConfigs.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/AddBizInResourcesHook.java
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/AddBizInResourcesHookTest.java
Labels: cla:yes, size/S

#961 merge master to 3.0.7
  pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/ExplodedBizArchive.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/EmbedClassPathArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/ExplodedBizArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/jar/JarUtilsTest.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizManagerServiceImpl.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/extension/ExtensionLoaderServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/ArkContainerTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/BaseTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/api/ArkClientTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/hook/TestAddBizToStaticDeployHook.java
  sofa-ark-parent/core-impl/container/src/test/resources/META-INF/services/sofa-ark/com.alipay.sofa.ark.spi.service.biz.AddBizToStaticDeployHook
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkConfigs.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizState.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/biz/AddBizToStaticDeployHook.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/ArkServiceLoader.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/ExtensionLoaderService.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/conf/ark/bootstrap.properties
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/conf/ark/bootstrap.yml
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/java/com/alipay/sofa/ark/plugin/mojo/ArkPluginMojo.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/test/java/com/alipay/sofa/ark/plugin/mojo/ArkPluginMojoTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/AddBizInResourcesHook.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/MasterBizEnvironmentHolder.java
  sofa-ark-parent/support/ark-support-starter/src/main/resources/META-INF/services/sofa-ark/com.alipay.sofa.ark.spi.service.biz.AddBizToStaticDeployHook
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/AddBizInResourcesHookTest.java
  sofa-ark-parent/support/ark-support-starter/src/test/resources/SOFA-ARK/biz/biz1-bootstrap-0.0.1-SNAPSHOT-ark-biz.jar
Labels: cla:yes, size/XL

#963 no using StringUtil by define subString
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/AddBizInResourcesHook.java
Labels: cla:yes, size/M

#962 merge master to 3.1.5
  pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/ExplodedBizArchive.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/EmbedClassPathArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/ExplodedBizArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/jar/JarUtilsTest.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/pipeline/HandleArchiveStage.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizManagerServiceImpl.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/extension/ExtensionLoaderServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/ArkContainerTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/BaseTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/api/ArkClientTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/hook/TestAddBizToStaticDeployHook.java
  sofa-ark-parent/core-impl/container/src/test/resources/META-INF/services/sofa-ark/com.alipay.sofa.ark.spi.service.biz.AddBizToStaticDeployHook
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkConfigs.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizState.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/biz/AddBizToStaticDeployHook.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/ArkServiceLoader.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/service/extension/ExtensionLoaderService.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/conf/ark/bootstrap.properties
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/conf/ark/bootstrap.yml
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/java/com/alipay/sofa/ark/plugin/mojo/ArkPluginMojo.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/test/java/com/alipay/sofa/ark/plugin/mojo/ArkPluginMojoTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/listener/ArkApplicationStartListener.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/AddBizInResourcesHook.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/MasterBizEnvironmentHolder.java
  sofa-ark-parent/support/ark-support-starter/src/main/resources/META-INF/services/sofa-ark/com.alipay.sofa.ark.spi.service.biz.AddBizToStaticDeployHook
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/AddBizInResourcesHookTest.java
  sofa-ark-parent/support/ark-support-starter/src/test/resources/SOFA-ARK/biz/biz1-bootstrap-0.0.1-SNAPSHOT-ark-biz.jar
Labels: cla:yes, size/XL

#964 modify switch web classloader loglevel to debug
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/web/SwitchClassLoaderFilter.java
Labels: cla:yes, size/XS

#965 modify switch web classloader loglevel to debug
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/web/SwitchClassLoaderFilter.java
Labels: cla:yes, size/XS

#966 modify switch web classloader loglevel to debug
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/web/SwitchClassLoaderFilter.java
Labels: cla:yes, size/XS

#967 release to 2.2.12
  pom.xml
Labels: cla:yes, size/XS

#969 release to 3.1.5
  pom.xml
Labels: cla:yes, size/XS

#968 release to 3.0.7
  pom.xml
Labels: cla:yes, size/XS

#972 新版模块瘦身
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/ModuleSlimConfig.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/ModuleSlimStrategy.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/model/ArkConfigHolder.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/utils/ParseUtils.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/ModuleSlimStrategyTest.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/ReflectionUtils.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java
Labels: cla:yes, size/XXL

#974 fixed sofa-ark-plugin-maven-plugin plugin version 3.0.1-SNAPSHOT to …
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
Labels: size/XS, First-time contributor, cla:no

#975 update version in plugin
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
Labels: cla:yes, size/XS

#976 update plugin version
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
Labels: cla:yes, size/XS
