Repository sofastack/sofa-ark, pull requests merged in 2024-03, with the labels that each got.

#850 update to 2.2.8-SNAPSHOT
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyWebServer.java
  sofa-ark-plugin/netty-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/S

#854 fix test error
  pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-support-starter/pom.xml
Labels: bug, cla:yes, size/M

#856 fix test error
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
Labels: bug, cla:yes, size/XS

#853 update guava version to aviod guava cache pin problem
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
Labels: cla:yes, size/XS, First-time contributor

#858 <fix> modify notes for javadoc
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkServletLegacyAutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoader.java
Labels: bug, cla:yes, size/XS

#860 update to 2.2.8
  pom.xml
Labels: cla:yes, size/XS

#861 merge from master to 3.0.x
  README.md
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyReactiveWebServerFactory.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyWebServer.java
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-plugin/netty-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/src/main/java/com/alipay/sofa/ark/web/embed/WebPluginActivator.java
Labels: cla:yes, size/M

#864 no maven tree when single bundle
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
Labels: question, cla:yes, size/XS

#867 fix missing in-direct lib when analysis dependencies by mvn tree
  pom.xml
Labels: bug, question, cla:yes, size/XS

#869 Update README.md
  README.md
Labels: cla:yes, size/XS

#873 update version
  pom.xml
Labels: cla:yes, size/XS

#872 update version
  pom.xml
Labels: cla:yes, size/XS

#874 add log for file not found
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/data/RandomAccessDataFile.java
Labels: cla:yes, size/XS

#876 simplify parse id from jar
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
Labels: cla:yes, size/L

#877 fix ark plugin
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/netty-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: bug, cla:yes, size/S

#878 parse artifact id with accuracy first
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
  sofa-ark-parent/core-impl/container/src/test/resources/sample-ark-plugin-common-0.5.1.jar
  sofa-ark-parent/core-impl/container/src/test/resources/sofa-ark-sample-springboot-ark-0.3.0.jar
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/DefaultClassLoaderHookTest.java
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sample-ark-plugin-0.5.0.jar
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sample-ark-plugin-common-0.5.1.jar
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sofa-ark-sample-springboot-ark-0.3.0.jar
Labels: cla:yes, size/M

#883 add start class in manifest
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryBizArchive.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/DirectoryBizArchiveTest.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
Labels: cla:yes, size/S

#881 <feature> add bizFailedEvent
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/event/EventTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/AfterBizFailedEvent.java
Labels: cla:yes, size/M

#885 add envs for biz starter
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/AbstractLauncher.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/MainMethodRunner.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/bootstrap/MainMethodRunnerTest.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/Biz.java
Labels: cla:yes, size/M

#887 add envs for install operation
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
Labels: cla:yes, size/S

#888 set args as empty array when args = null for startup
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/MainMethodRunner.java
Labels: question, cla:yes, size/XS

#889 add bizStateChangeLog
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/MainMethodRunner.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
Labels: cla:yes, size/L

#890 1、增加zookeeper注册节点环境变量，新增配置参数com.alipay.sofa.ark.config.env。默认为sofa-ark
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/zk/ZookeeperConfigActivator.java
Labels: cla:yes, size/L, First-time contributor

#886 adapt for jdk21
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/pom.xml
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/base/BaseTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/CentralDirectoryFileHeaderTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/CentralDirectoryParserTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarFileTest.java
  sofa-ark-parent/core-impl/container/pom.xml
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-plugin-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkCompositeReactorHttpHandlerAdapter.java
  sofa-ark-parent/support/ark-support-starter/pom.xml
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/M

#891 fix no ark log in ark container
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
Labels: bug, cla:yes, size/M

#892 update biz state record name
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
Labels: cla:yes, size/S

#893 rename typo
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
Labels: cla:yes, size/M

#894 add logging.file.path to get config from user app config
  pom.xml
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
Labels: cla:yes, size/XS

#895 merge master to 3.0.4
  README.md
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/AbstractLauncher.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/MainMethodRunner.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryBizArchive.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/data/RandomAccessDataFile.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/bootstrap/MainMethodRunnerTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/DirectoryBizArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/event/EventTest.java
  sofa-ark-parent/core-impl/container/src/test/resources/sample-ark-plugin-common-0.5.1.jar
  sofa-ark-parent/core-impl/container/src/test/resources/sofa-ark-sample-springboot-ark-0.3.0.jar
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/AfterBizFailedEvent.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/Biz.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/CompatibleSpringBoot1AutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/endpoint/IntrospectBizEndpoint.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkAutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainerFactory.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainerTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatServletWebServerFactoryTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/java/com/alipay/sofa/ark/test/springboot1/IntrospectBizEndpointOnArkDisabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/java/com/alipay/sofa/ark/test/springboot1/IntrospectBizEndpointOnArkEnabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/resources/logback.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/CompatibleSpringBoot2AutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/endpoint/IntrospectBizEndpoint.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/java/com/alipay/sofa/ark/test/springboot2/SpringBoot2IntrospectBizEndpointOnArkDisabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/java/com/alipay/sofa/ark/test/springboot2/SpringBoot2IntrospectBizEndpointOnArkEnabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/resources/logback.xml
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/DefaultClassLoaderHookTest.java
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sample-ark-plugin-0.5.0.jar
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sample-ark-plugin-common-0.5.1.jar
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sofa-ark-sample-springboot-ark-0.3.0.jar
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/zk/ZookeeperConfigActivator.java
  sofa-ark-plugin/netty-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/XXL
