Repository sofastack/sofa-ark, pull requests merged in 2024-12, with the labels that each got.

#1044 set logback context name=default
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/adapter/ArkLogbackContextSelector.java
  sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/adapter/ArkLogbackContextSelectorTest.java
Labels: cla:yes, size/XS

#1042 add param to determine whether unpack biz when install
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
Labels: question, cla:yes, size/M, First-time contributor

#1046 add event after all biz startup when bizs playback in base restart
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/AfterAllBizStartupEvent.java
Labels: question, cla:yes, size/M

#1031 fix: 修复委托基座加载资源过程中，模块未声明的依赖存在该资源时，无法正确获取资源(#1030)
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/DelegateToMasterBizClassLoaderHook.java
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/DefaultClassLoaderHookTest.java
Labels: bug, cla:yes, First-time contributor, size/S

#1029 feat: 支持模块启动时通过传递env参数动态指定模块的启动类 (#999)
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/api/ArkClientTest.java
  sofa-ark-parent/core-impl/container/src/test/resources/sample-ark-5.0.0-ark-biz.jar
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
Labels: bug, cla:yes, size/M, First-time contributor

#1050 merge 2.2.16 to 3.1.9
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/api/ArkClientTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
  sofa-ark-parent/core-impl/container/src/test/resources/sample-ark-5.0.0-ark-biz.jar
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/AfterAllBizStartupEvent.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/common/DelegateToMasterBizClassLoaderHook.java
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/DefaultClassLoaderHookTest.java
Labels: cla:yes, size/L

#1051 update to 2.2.16
  pom.xml
Labels: cla:yes, size/XS

#1052 update to 3.1.9
  pom.xml
Labels: cla:yes, size/XS

#1053 update to 3.1.9
  pom.xml
Labels: cla:yes, size/XS
