Repository sofastack/sofa-ark, pull requests merged in 2024-06, with the labels that each got.

#937 update to 3.0.6
  pom.xml
Labels: cla:yes, size/XS

#938 update to 3.1.4
  pom.xml
Labels: cla:yes, size/XS

#939 not stop after startup failure
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/api/ArkClientTest.java
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
Labels: cla:yes, size/L

#936 fix：sofa-ark-plugin-maven-plugin remove unnecessary shade lib
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/java/com/alipay/sofa/ark/plugin/mojo/ArkPluginMojo.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/test/java/com/alipay/sofa/ark/plugin/mojo/ArkPluginMojoTest.java
Labels: bug, cla:yes, First-time contributor, size/S

#943 warn when mark and delete biz temp work failed
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizState.java
Labels: question, cla:yes, size/M

#944 close the biz classloader
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/api/ArkClientTest.java
Labels: cla:yes, First-time contributor, size/S

#947 update asm for jdk21
  sofa-ark-bom/pom.xml
Labels: cla:yes, size/XS

#951 Close the FileInputStream of the MANIFEST.MF file
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/ExplodedBizArchive.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/ExplodedBizArchiveTest.java
Labels: cla:yes, size/S

#953 close the JarFile
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/jar/JarUtilsTest.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/AbstractClasspathClassLoader.java
Labels: cla:yes, size/S
