Repository sofastack/sofa-ark, pull requests merged in 2024-04, with the labels that each got.

#896 merge 2.2.9 to 3.1.2
  README.md
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/AbstractLauncher.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/bootstrap/MainMethodRunner.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryBizArchive.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/data/RandomAccessDataFile.java
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/jar/JarUtils.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/bootstrap/MainMethodRunnerTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/DirectoryBizArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/test/jar/JarUtilsTest.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/ArkContainer.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/classloader/BizClassLoaderTest.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/service/event/EventTest.java
  sofa-ark-parent/core-impl/container/src/test/resources/sample-ark-plugin-common-0.5.1.jar
  sofa-ark-parent/core-impl/container/src/test/resources/sofa-ark-sample-springboot-ark-0.3.0.jar
  sofa-ark-parent/core/api/src/main/java/com/alipay/sofa/ark/api/ArkClient.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/event/biz/AfterBizFailedEvent.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/Biz.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/CompatibleSpringBoot1AutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/endpoint/IntrospectBizEndpoint.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkAutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainer.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainerFactory.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatEmbeddedServletContainerTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/java/com/alipay/sofa/ark/springboot1/web/ArkTomcatServletWebServerFactoryTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/java/com/alipay/sofa/ark/test/springboot1/IntrospectBizEndpointOnArkDisabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/java/com/alipay/sofa/ark/test/springboot1/IntrospectBizEndpointOnArkEnabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/test/resources/logback.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/CompatibleSpringBoot2AutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/endpoint/IntrospectBizEndpoint.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/java/com/alipay/sofa/ark/test/springboot2/SpringBoot2IntrospectBizEndpointOnArkDisabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/java/com/alipay/sofa/ark/test/springboot2/SpringBoot2IntrospectBizEndpointOnArkEnabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/resources/logback.xml
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/DefaultClassLoaderHookTest.java
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sample-ark-plugin-0.5.0.jar
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sample-ark-plugin-common-0.5.1.jar
  sofa-ark-parent/support/ark-support-starter/src/test/resources/sofa-ark-sample-springboot-ark-0.3.0.jar
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/Repackager.java
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/config-ark-plugin/src/main/java/com/alipay/sofa/ark/config/zk/ZookeeperConfigActivator.java
  sofa-ark-plugin/netty-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/XXL

#897 优化biz信息显示
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
Labels: cla:yes, size/S

#899 优化biz信息显示 (#897)
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
Labels: cla:yes, size/S

#898 优化biz信息显示 (#897)
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
Labels: cla:yes, size/S

#900 update to 2.2.9
  pom.xml
Labels: cla:yes, size/XS

#902 update to 3.1.2
  pom.xml
Labels: cla:yes, size/XS

#901 update version to 3.0.4
  pom.xml
Labels: cla:yes, size/XS

#907 1. 删除前先标记文件夹已经被回收 2.即使删除失败也不会影响下次模块安装
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
Labels: cla:yes, size/M, First-time contributor

#912 sofa-ark-maven-plugin supports jdk17 record symbol
  pom.xml
  sofa-ark-parent/support/ark-tools/src/main/java/com/alipay/sofa/ark/tools/MainClassFinder.java
Labels: bug, cla:yes, size/XS

#913 switch classLoader for web biz to using same bizclassloader for startup and runtime
  .github/workflows/linux_unit_test.yml
  .github/workflows/windows_unit_test.yml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkServletAutoConfiguration.java
  sofa-ark-plugin/web-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/src/main/java/com/alipay/sofa/ark/web/embed/tomcat/SwitchClassLoaderAutoConfiguration.java
  sofa-ark-plugin/web-ark-plugin/src/main/resources/META-INF/spring.factories
  sofa-ark-plugin/web-ark-plugin/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: cla:yes, size/L

#916 update version to 2.2.10-SNAPSHOT
  pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/S

#917 fix codecov missing
  .github/workflows/linux_unit_test.yml
  .github/workflows/windows_unit_test.yml
Labels: bug, cla:yes, size/XS

#919 support customize outputfile when package ark biz
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
Labels: question, cla:yes, size/S

#920 support cutomize outputFile when ark maven
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
Labels: question, cla:yes, size/S
