Repository sofastack/sofa-ark, pull requests merged in 2024-05, with the labels that each got.

#923 merge master to 3.1.3
  .github/workflows/linux_unit_test.yml
  .github/workflows/windows_unit_test.yml
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/PluginClassLoader.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/CompatibleSpringBoot2AutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/endpoint/IntrospectBizEndpoint.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/java/com/alipay/sofa/ark/test/springboot2/SpringBoot2IntrospectBizEndpointOnArkDisabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/java/com/alipay/sofa/ark/test/springboot2/SpringBoot2IntrospectBizEndpointOnArkEnabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/resources/logback.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/runner/ArkBootEmbedRunner.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/runner/ArkBootRunner.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkTomcatWebServer.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/ArkBootRunnerTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/ArkBootTestNGTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/springboot/BaseSpringApplication.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/listener/ArkTestNGAlterSuiteListener.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/listener/ArkTestNGInvokedMethodListener.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/listener/TestNGOnArkEmbeded.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/runner/ArkJUnit4EmbedRunner.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/runner/ArkJUnit4Runner.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/runner/JUnitExecutionListener.java
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/runner/ArkJUnit4RunnerTest.java
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/src/main/java/com/alipay/sofa/ark/web/embed/tomcat/SwitchClassLoaderAutoConfiguration.java
  sofa-ark-plugin/web-ark-plugin/src/main/resources/META-INF/spring.factories
  sofa-ark-plugin/web-ark-plugin/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: cla:yes, size/XL

#922 merge master to 3.0.5
  .github/workflows/linux_unit_test.yml
  .github/workflows/windows_unit_test.yml
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/PluginClassLoader.java
  sofa-ark-parent/core-impl/container/src/test/java/com/alipay/sofa/ark/container/model/BizModelTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/constant/Constants.java
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot1/src/main/java/com/alipay/sofa/ark/springboot1/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/CompatibleSpringBoot2AutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/endpoint/IntrospectBizEndpoint.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/java/com/alipay/sofa/ark/springboot2/web/SwitchClassLoaderFilter.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/resources/META-INF/spring.factories
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/java/com/alipay/sofa/ark/test/springboot2/SpringBoot2IntrospectBizEndpointOnArkDisabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/java/com/alipay/sofa/ark/test/springboot2/SpringBoot2IntrospectBizEndpointOnArkEnabledTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-compatible-springboot2/src/test/resources/logback.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/runner/ArkBootEmbedRunner.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/runner/ArkBootRunner.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkTomcatWebServer.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/ArkBootRunnerTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/ArkBootTestNGTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/springboot/BaseSpringApplication.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/listener/ArkTestNGAlterSuiteListener.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/listener/ArkTestNGInvokedMethodListener.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/listener/TestNGOnArkEmbeded.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/runner/ArkJUnit4EmbedRunner.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/runner/ArkJUnit4Runner.java
  sofa-ark-parent/support/ark-support-starter/src/main/java/com/alipay/sofa/ark/support/runner/JUnitExecutionListener.java
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/runner/ArkJUnit4RunnerTest.java
  sofa-ark-parent/support/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/src/main/java/com/alipay/sofa/ark/web/embed/tomcat/SwitchClassLoaderAutoConfiguration.java
  sofa-ark-plugin/web-ark-plugin/src/main/resources/META-INF/spring.factories
  sofa-ark-plugin/web-ark-plugin/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: cla:yes, size/XL

#918 优化排包配置
  sofa-ark-bom/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/src/main/resources/ark.properties
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/src/main/resources/ark.yml
Labels: cla:yes, size/L

#911 runtime中静态合并部署时多模块并行执行createTempDir时异常
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/FileUtils.java
Labels: cla:yes, size/XS, First-time contributor

#925 release 3.1.3
  pom.xml
Labels: cla:yes, size/XS

#924 release 3.0.5
  pom.xml
Labels: cla:yes, size/XS

#926 add string contains
  pom.xml
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/StringUtils.java
  sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/StringUtilsTest.java
Labels: cla:yes, size/S

#927 fix ReactiveWebServerFactoryAutoConfiguration not support sprintboot 1.x
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkReactiveAutoConfiguration.java
Labels: bug, cla:yes, size/XS

#928 add biz jar url in biz module
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/MultiArkBootRunnerTest.java
Labels: cla:yes, size/S

#931 update netty version
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
Labels: cla:yes, size/XS, First-time contributor

#930 update to 2.2.11
  pom.xml
Labels: cla:yes, size/XS

#932 merge master to 3.0.6
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/FileUtils.java
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/StringUtils.java
  sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/StringUtilsTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/src/main/resources/ark.properties
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/src/main/resources/ark.yml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkReactiveAutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/MultiArkBootRunnerTest.java
Labels: cla:yes, size/XXL

#933 merge master to 3.1.4
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/model/BizModel.java
  sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/biz/BizFactoryServiceImpl.java
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/FileUtils.java
  sofa-ark-parent/core/common/src/main/java/com/alipay/sofa/ark/common/util/StringUtils.java
  sofa-ark-parent/core/common/src/test/java/com/alipay/sofa/ark/common/util/StringUtilsTest.java
  sofa-ark-parent/core/spi/src/main/java/com/alipay/sofa/ark/spi/model/BizInfo.java
  sofa-ark-parent/support/ark-maven-plugin/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/java/com/alipay/sofa/ark/boot/mojo/RepackageMojoTest.java
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/src/main/resources/ark.properties
  sofa-ark-parent/support/ark-maven-plugin/src/test/resources/baseDir/src/main/resources/ark.yml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/ArkReactiveAutoConfiguration.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/MultiArkBootRunnerTest.java
Labels: cla:yes, size/L

#934 fix multi ark boot runner test
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/MultiArkBootRunnerTest.java
Labels: bug, cla:yes, size/S
