Repository sofastack/sofa-ark, pull requests merged in 2024-02, with the labels that each got.

#841 Merge spring 3.2
  pom.xml
  sofa-ark-bom/pom.xml
  sofa-ark-parent/core-impl/archive/src/main/java/com/alipay/sofa/ark/loader/DirectoryContainerArchive.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/EmbedClassPathArchiveTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/jar/ZipInflaterInputStreamTest.java
  sofa-ark-parent/core/common/pom.xml
  sofa-ark-parent/support/ark-maven-plugin/src/main/java/com/alipay/sofa/ark/boot/mojo/RepackageMojo.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/pom.xml
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoader.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/loader/JarLauncher.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyReactiveWebServerFactory.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/springboot/loader/CachedLaunchedURLClassLoaderTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/test/java/com/alipay/sofa/ark/test/ArkBootRunnerTest.java
  sofa-ark-plugin/config-ark-plugin/pom.xml
  sofa-ark-plugin/web-ark-plugin/pom.xml
Labels: cla:yes, size/L

#826 Add ut 0110
  .gitignore
  pom.xml
  sofa-ark-plugin/pom.xml
Labels: cla:yes, size/S

#843 netty support 0.9.x
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/jar/JarURLConnectionTest.java
  sofa-ark-parent/core-impl/archive/src/test/java/com/alipay/sofa/ark/loader/jar/ZipInflaterInputStreamTest.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/META-INF/MANIFEST.MF
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/main/java/com/alipay/sofa/ark/plugin/mojo/ExportConfig.java
  sofa-ark-parent/support/ark-plugin-maven-plugin/src/test/java/com/alipay/sofa/ark/plugin/mojo/ArkPluginMojoTest.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyReactiveWebServerFactory.java
  sofa-ark-parent/support/ark-springboot-integration/ark-springboot-starter/src/main/java/com/alipay/sofa/ark/springboot/web/ArkNettyWebServer.java
  sofa-ark-parent/support/ark-support-starter/src/test/java/com/alipay/sofa/ark/support/thread/LaunchRunnerTest.java
Labels: cla:yes, size/M

#844 release 3.0.2
  pom.xml
Labels: cla:yes, size/XS

#845 release 3.1.x
  pom.xml
Labels: cla:yes, size/XS
